param(
    [string]$BuildDirectory = "build/phase5-release",
    [ValidateSet("Debug", "Release", "RelWithDebInfo", "MinSizeRel")]
    [string]$Configuration = "Release",
    [int]$Device = 0,
    [string]$CMake = "",
    [ValidateRange(30, 3600)]
    [int]$TimeoutSeconds = 600
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Assert-Condition {
    param([bool]$Condition, [string]$Message)
    if (-not $Condition) {
        throw "Phase 5 SDK v2 hardware smoke failed: $Message"
    }
}

function Resolve-CMake {
    param([string]$Requested)
    if ($Requested) {
        $resolved = Resolve-Path -LiteralPath $Requested -ErrorAction Stop
        return $resolved.Path
    }
    $command = Get-Command cmake -ErrorAction SilentlyContinue
    if ($null -ne $command) {
        return $command.Source
    }
    $visualStudioCMake =
        "C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"
    if (Test-Path -LiteralPath $visualStudioCMake -PathType Leaf) {
        return $visualStudioCMake
    }
    throw "Phase 5 SDK v2 hardware smoke failed: cmake was not found"
}

Assert-Condition ([Environment]::OSVersion.Platform -eq [PlatformID]::Win32NT) `
    "the mandatory SDK gate requires Windows WDDM"
Assert-Condition ([Environment]::Is64BitProcess) "the SDK gate requires a 64-bit process"
Assert-Condition ($Device -ge 0) "device ordinal must be non-negative"
Assert-Condition ($TimeoutSeconds -ge 30) "timeout must be at least 30 seconds"

$repositoryRoot = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
$buildCandidate = if ([IO.Path]::IsPathRooted($BuildDirectory)) {
    $BuildDirectory
} else {
    Join-Path $repositoryRoot $BuildDirectory
}
$buildRoot = (Resolve-Path -LiteralPath $buildCandidate -ErrorAction Stop).Path
$cmakePath = Resolve-CMake -Requested $CMake

# A Ninja build generated by Visual Studio still needs the MSVC include/library environment in
# the invoking process. Rehydrate it when the gate is launched from an ordinary PowerShell.
if (-not (Get-Command cl.exe -ErrorAction SilentlyContinue)) {
    $vsDevShell =
        "C:\Program Files\Microsoft Visual Studio\18\Community\Common7\Tools\Launch-VsDevShell.ps1"
    Assert-Condition (Test-Path -LiteralPath $vsDevShell -PathType Leaf) `
        "Visual Studio developer shell was not found"
    & $vsDevShell -Arch amd64 -HostArch amd64 -NoLogo -SkipAutomaticLocation
}

& $cmakePath --build $buildRoot --config $Configuration `
    --target xvram-sdk-v2-hardware-smoke --parallel
Assert-Condition ($LASTEXITCODE -eq 0) "the SDK v2 smoke target did not build"

$helperName = "xvram-sdk-v2-hardware-smoke.exe"
$cachePath = Join-Path $buildRoot "CMakeCache.txt"
Assert-Condition (Test-Path -LiteralPath $cachePath -PathType Leaf) `
    "the build directory has no CMake cache"
$cache = @(Get-Content -LiteralPath $cachePath)
$multiConfiguration = @($cache | Where-Object {
    $_ -match '^CMAKE_CONFIGURATION_TYPES:[^=]+=.+'
}).Count -ne 0
if ($multiConfiguration) {
    $helperPath = Join-Path (Join-Path (Join-Path $buildRoot "tests") $Configuration) $helperName
    $sdkPath = Join-Path (Join-Path $buildRoot $Configuration) "xvram.dll"
} else {
    $buildType = @($cache | Where-Object { $_ -match '^CMAKE_BUILD_TYPE:[^=]+=' })
    Assert-Condition ($buildType.Count -eq 1 -and `
        ($buildType[0] -split '=', 2)[1] -eq $Configuration) `
        "single-configuration build does not match the requested $Configuration"
    $helperPath = Join-Path (Join-Path $buildRoot "tests") $helperName
    $sdkPath = Join-Path $buildRoot "xvram.dll"
}
Assert-Condition (Test-Path -LiteralPath $helperPath -PathType Leaf) `
    "unable to locate the configured helper: $helperPath"
Assert-Condition (Test-Path -LiteralPath $sdkPath -PathType Leaf) `
    "unable to locate the matching production SDK: $sdkPath"
$helper = Get-Item -LiteralPath $helperPath
$sdkLibrary = Get-Item -LiteralPath $sdkPath
$adjacentSdk = Join-Path $helper.Directory.FullName "xvram.dll"
if (Test-Path -LiteralPath $adjacentSdk -PathType Leaf) {
    # Windows searches the executable directory before PATH; reject a stale shadow copy.
    Assert-Condition ((Get-FileHash -LiteralPath $adjacentSdk -Algorithm SHA256).Hash -eq `
        (Get-FileHash -LiteralPath $sdkPath -Algorithm SHA256).Hash) `
        "a different xvram.dll beside the helper would shadow the selected SDK"
}

$stdoutPath = [IO.Path]::GetTempFileName()
$stderrPath = [IO.Path]::GetTempFileName()
$savedPath = $env:PATH
try {
    $env:PATH = "$($sdkLibrary.Directory.FullName);$savedPath"
    $process = Start-Process -FilePath $helper.FullName `
        -ArgumentList @("--device", [string]$Device) `
        -WorkingDirectory $helper.Directory.FullName `
        -RedirectStandardOutput $stdoutPath `
        -RedirectStandardError $stderrPath `
        -WindowStyle Hidden `
        -PassThru
    if (-not $process.WaitForExit($TimeoutSeconds * 1000)) {
        Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue
        $process.WaitForExit()
        throw "Phase 5 SDK v2 hardware smoke failed: helper exceeded $TimeoutSeconds seconds"
    }
    $process.WaitForExit()
    $stdout = @(Get-Content -LiteralPath $stdoutPath -ErrorAction SilentlyContinue)
    $stderr = @(Get-Content -LiteralPath $stderrPath -ErrorAction SilentlyContinue)
    $stdout | ForEach-Object { Write-Host $_ }
    $stderr | ForEach-Object { Write-Host $_ }
    Assert-Condition ($process.ExitCode -eq 0) "helper exited with code $($process.ExitCode)"

    $jsonLines = @($stdout | Where-Object { $_.TrimStart().StartsWith("{") })
    Assert-Condition ($jsonLines.Count -eq 1) "helper did not emit exactly one JSON result"
    $result = $jsonLines[0] | ConvertFrom-Json
    Assert-Condition ($result.report_type -eq "xvram.sdk_v2_hardware_smoke") `
        "unexpected helper report type"
    Assert-Condition ($result.status -eq "completed") "the SDK v2 proof did not complete"
    Assert-Condition ([uint64]$result.logical_bytes -eq 805306368) `
        "the bounded twelve-chunk workload size changed"
    Assert-Condition ([uint64]$result.mappings -gt 0) "no CUDA VMM mapping was observed"
    Assert-Condition ([uint64]$result.mappings -eq [uint64]$result.unmaps) `
        "mapping and unmapping counts differ"
    Assert-Condition ([uint64]$result.handle_reuses -gt 0) "physical handles were not reused"
    Assert-Condition ([uint64]$result.dirty_evictions -gt 0) "dirty eviction was not exercised"
    Assert-Condition ([uint64]$result.compression_commits -gt 0) `
        "authoritative compressed backing was not committed"
    Assert-Condition ([uint64]$result.logical_h2d_bytes -gt [uint64]$result.pcie_h2d_bytes) `
        "compressed H2D did not reduce PCIe payload"
} finally {
    $env:PATH = $savedPath
    foreach ($temporaryPath in @($stdoutPath, $stderrPath)) {
        $resolvedTemporary = [IO.Path]::GetFullPath($temporaryPath)
        $systemTemporary = [IO.Path]::GetFullPath([IO.Path]::GetTempPath())
        if ($resolvedTemporary.StartsWith($systemTemporary, [StringComparison]::OrdinalIgnoreCase) -and
            (Test-Path -LiteralPath $resolvedTemporary -PathType Leaf)) {
            Remove-Item -LiteralPath $resolvedTemporary -Force
        }
    }
}

Write-Host "Phase 5 SDK v2 production hardware smoke completed successfully."
